//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceabilityV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string IP { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string MAC { get; set; }
        public Nullable<int> SwitchPort { get; set; }
        public string Switch { get; set; }
        public string SerialNumber { get; set; }
        public string HardwareVersion { get; set; }
        public string SoftwareVersion { get; set; }
        public string StorageInformation { get; set; }
        public string NetworkInformation { get; set; }
        public string LocalWebServerUrlPORT { get; set; }
        public Nullable<bool> RequiresUpdate { get; set; }
        public Nullable<System.DateTime> LastCheckin { get; set; }
        public string LastReportedStatus { get; set; }
        public string NetworkConfigIP { get; set; }
        public string NetworkConfigSubnet { get; set; }
        public string NetworkConfigGateway { get; set; }
        public string NetworkConfigDNS { get; set; }
        public Nullable<bool> LockedOut { get; set; }
        public string LockedOutBy { get; set; }
        public Nullable<System.DateTime> LockedOutOn { get; set; }
        public string SecurityKey { get; set; }
        public string CurrentOperatorId { get; set; }
        public Nullable<bool> RequiresSupport { get; set; }
        public Nullable<int> Waypoint { get; set; }
    }
}
