//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceabilityV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class HandlingUnit
    {
        public string SSCC { get; set; }
        public string WERKS { get; set; }
        public string MATNR { get; set; }
        public string ScannedCode { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public string Batch { get; set; }
        public string Horse { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsUploaded { get; set; }
    }
}
