//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceabilityV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuedLabel
    {
        public int Id { get; set; }
        public string SSCC { get; set; }
        public string BusinessUnit { get; set; }
        public string Country { get; set; }
        public string JulianDate { get; set; }
        public Nullable<System.DateTime> DateString { get; set; }
        public string WERKS { get; set; }
        public string Batch { get; set; }
        public Nullable<System.DateTime> BestBefore { get; set; }
        public string MATNR { get; set; }
        public string MaterialDescription { get; set; }
        public string MaterialGTIN { get; set; }
        public Nullable<decimal> MaterialQtyLevel1 { get; set; }
        public Nullable<decimal> MaterialQtyCON { get; set; }
        public Nullable<decimal> MaterialNetWt { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string ZPL { get; set; }
    }
}
