//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceabilityV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator
    {
        public string EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string Code { get; set; }
        public Nullable<int> WaypointID { get; set; }
    }
}
