//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceabilityV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Handling_Units = new HashSet<Handling_Units>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> PLU { get; set; }
        public string Type { get; set; }
        public string Packaging { get; set; }
        public Nullable<int> ConsumerUnits { get; set; }
        public Nullable<int> SalesUnits { get; set; }
        public Nullable<decimal> TargetWeight { get; set; }
        public string UOM { get; set; }
        public string TareWeight { get; set; }
        public string ConsumerBarcode { get; set; }
        public string SalesUnitBarcode { get; set; }
        public string Commodity { get; set; }
        public string ProducedBy { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> HUTargetWeight { get; set; }
        public Nullable<int> ExpiryDays { get; set; }
        public Nullable<int> Labels { get; set; }
        public Nullable<int> QCSampleSize { get; set; }
        public string GTin_Con { get; set; }
        public string GTIN_HU { get; set; }
        public string GTIN_Level1 { get; set; }
        public string GTIN_Level2 { get; set; }
        public Nullable<decimal> ConsPerHUNum { get; set; }
        public Nullable<int> ConsPerHUInt { get; set; }
        public string SAPDeletionFlagX { get; set; }
        public string WERKS { get; set; }
        public string MATNR { get; set; }
        public string GTIN_SalesUOM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Handling_Units> Handling_Units { get; set; }
    }
}
