//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceabilityV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSCCNumberBank
    {
        public string NumberBank { get; set; }
        public string Range { get; set; }
        public string LastIssued { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Reserved { get; set; }
        public Nullable<System.DateTime> Released { get; set; }
        public Nullable<System.DateTime> Depleted { get; set; }
        public Nullable<int> Waypoint { get; set; }
        public string Device { get; set; }
        public string Status { get; set; }
    }
}
