//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceabilityV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waypoint
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string UOM { get; set; }
        public string LoadCapcity { get; set; }
        public Nullable<bool> HasPrinter { get; set; }
        public Nullable<bool> HasScanner { get; set; }
        public Nullable<bool> RepackStation { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> ToWaypoint { get; set; }
        public Nullable<bool> VariableWaypoint { get; set; }
    }
}
