//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceabilityV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class zTraceIn_SAPMaterials
    {
        public string SYSID { get; set; }
        public string MANDT { get; set; }
        public string WERKS { get; set; }
        public string MATNR { get; set; }
        public string MAKTX { get; set; }
        public string GTIN_CON { get; set; }
        public string GTIN_HU { get; set; }
        public string GTIN_Level1 { get; set; }
        public string GTIN_Level2 { get; set; }
        public decimal NetWt_CON { get; set; }
        public decimal NetWt_HU { get; set; }
        public Nullable<decimal> NetWt_Level1 { get; set; }
        public Nullable<decimal> NetWt_Level2 { get; set; }
        public Nullable<decimal> TareWt_CON { get; set; }
        public Nullable<decimal> TareWt_HU { get; set; }
        public Nullable<decimal> TareWt_Level1 { get; set; }
        public Nullable<decimal> TareWt_Level2 { get; set; }
        public decimal HUQty_CON { get; set; }
        public decimal HUQty_Level1 { get; set; }
        public decimal HUQty_Level2 { get; set; }
        public string SAPUOM_CON { get; set; }
        public string SAPUOM_HU { get; set; }
        public string SAPUOM_Level1 { get; set; }
        public string SAPUOM_Level2 { get; set; }
        public string SAPUOM_Base { get; set; }
        public string SAPUOM_Sales { get; set; }
        public string QCUOM { get; set; }
        public string WtCatUOM { get; set; }
        public string ProductType { get; set; }
        public decimal ProductWtCat { get; set; }
        public string BulkFlag { get; set; }
        public Nullable<System.DateTime> DateFirstAdded { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public Nullable<decimal> ReadStatus { get; set; }
        public string Retired { get; set; }
        public Nullable<System.DateTime> RetirementDate { get; set; }
        public string GTIN_SalesUOM { get; set; }
    }
}
