//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceabilityV3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zzSAPIntegrationTSH_WBEntities : DbContext
    {
        public zzSAPIntegrationTSH_WBEntities()
            : base("name=zzSAPIntegrationTSH_WBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<zTraceIn_SAPMaterials> zTraceIn_SAPMaterials { get; set; }
    }
}
